# Standards: 0.11
---

# 6.1.1 Audit system file permissions

- name: 6.1.1 - Audit system file permissions
  command: rpm -Va --nomtime --nosize --nomd5 --nolinkto
  register: audit_6_1_1
  no_log: True
  when: not in_vagrant
  tags:
    - level-2
    - section-6
    - "6.1.1"
    - scored

- name: 6.1.1 - Audit system file permissions (within Vagrant)
  command: rpm -Va --nomtime --nosize --nomd5 --nolinkto | egrep -v '/usr/lib64/python.../site-packages'
  register: audit_6_1_1
  no_log: True
  when: in_vagrant
  tags:
    - level-2
    - section-6
    - "6.1.1"
    - scored

- name: 6.1.1 - Audit system file permissions
  fail:
    # msg: "{{ audit_6_1_1.stdout }}"
    msg: "system file permissions audit failed"
  when:
    - audit_6_1_1.stdout_lines is defined and audit_6_1_1.stdout_lines|length > 0
    - fail_on_manual_remediation_actions
  tags:
    - level-2
    - section-6
    - "6.1.1"
    - scored

- name: 6.1.1 - Audit system file permissions
  debug:
    msg: "*** ACTION REQUIRED *** {{ audit_6_1_1.stdout }}"
  when:
    - audit_6_1_1.stdout_lines is defined and audit_6_1_1.stdout_lines|length > 0
    - not fail_on_manual_remediation_actions
  tags:
    - level-2
    - section-6
    - "6.1.1"
    - scored
