---

# 4.1.1.3 Ensure audit logs are not automatically deleted (Scored)
- name: 4.1.1.3 Ensure audit logs are not automatically deleted (Scored)
  command: grep max_log_file_action "{{ audit_log_file }}" # /etc/audit/auditd.conf
  register: audit_max_log_file_action
  tags:
    - level-1
    - section-4
    - "4.1.1.3"
    - scored

- name: Display the configured max log file action
  debug:
    var: audit_max_log_file_action
