---

# 4.1.2 Ensure auditd service is enabled (Scored)

- name: 4.1.2 Ensure auditd service is enabled (Scored)
  service:
    name: "auditd"
    enabled: true
  tags:
    - level-1
    - section-4
    - "4.1.2"
    - scored
