# Standards: 0.11
---

# 5.2.15 - Ensure only strong key exhcnage algorithms are used

- include: stat_sshd_config.yml
  tags:
    - level-1
    - section-5
    - "5.2.15"
    - scored

- name: 5.2.15 - Ensure only approved key exhcnage algorithms are used
  lineinfile:
    regexp: "^KexAlgorithms\\s+"
    line: "KexAlgorithms {{ cis_sshd_kex_algos }}"
    dest: "{{ cis_sshd_config_filename }}"
  when: sshd_config.stat.exists
  notify:
    - Restart sshd
  tags:
    - level-1
    - section-5
    - "5.2.15"
    - scored
