# Standards: 0.11
---

# 5.2.13 - Ensure only strong ciphers are used

- include: stat_sshd_config.yml
  tags:
    - level-1
    - section-5
    - "5.2.13"
    - scored

- name: 5.2.13 - Ensure only strong ciphers are used
  lineinfile:
    regexp: "^Ciphers\\s+"
    line: "Ciphers {{ cis_sshd_ciphers }}"
    dest: "{{ cis_sshd_config_filename }}"
  when: sshd_config.stat.exists
  notify:
    - Restart sshd
  tags:
    - level-1
    - section-5
    - "5.2.13"
    - scored
